name: Build

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2.3.5
            -   uses: actions/setup-dotnet@v5
                with:
                    dotnet-version: |
                        6.0.x
                        8.0.x
            -   name: Checkout Il2CppInterop
                uses: actions/checkout@v3
                with:
                    repository: krulci/Il2CppInterop.PR
                    path: repositories/Il2CppInterop

            -   name: Checkout Il2CppDumper
                uses: actions/checkout@v3
                with:
                    repository: ${{ github.repository_owner }}/Il2CppDumper
                    path: repositories/Il2CppDumper

            -   name: Build and Pack Locally
                run: |
                    mkdir -p ./LocalPackages
                    echo '<Project></Project>' > repositories/Directory.Build.props
                    dotnet build repositories/Il2CppInterop/Il2CppInterop.sln -c Release
                    dotnet build repositories/Il2CppDumper/Il2CppDumper.sln -c Release
                    dotnet pack repositories/Il2CppInterop/Il2CppInterop.sln -c Release -o ./LocalPackages
                    dotnet pack repositories/Il2CppDumper/Il2CppDumper.sln -c Release -o ./LocalPackages
            -   name: Build
                run: |
                    ./build.sh --target Publish
            -   name: Upload Artifacts
                uses: actions/upload-artifact@v4
                with:
                    path: "./bin/dist/*.zip"
                    name: "BepInEx_CI"
